#pragma once

#define TAPPING_TERM 200
#define TAP_CODE_DELAY 10
#define UNICODE_SELECTED_MODES UC_LNX

#define MOUSEKEY_DELAY 32
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 20
#define MOUSEKEY_MAX_SPEED 1
#define MOUSEKEY_TIME_TO_MAX 60

#define MOUSEKEY_WHEEL_INTERVAL 16
#define MOUSEKEY_WHEEL_DELAY 100
