#pragma once

#define TAPPING_TERM 200
#define TAP_CODE_DELAY 10
#define UNICODE_SELECTED_MODES UC_LNX

#define MOUSEKEY_DELAY 100
#define MOUSEKEY_INTERVAL 25
#define MOUSEKEY_MOVE_DELTA 10
#define MOUSEKEY_MAX_SPEED 3
